export const FETCH_USERS_REQUEST = 'FETCH_CUSTOMER_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_CUSTOMER_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_CUSTOMER_FAILURE'
export const ACTION_TYPE={
    CREATE:'CREATE',
    UPDATE:'UPDATE',
    DELETE:'DELETE',
    FETCH_ALL:'FETCH_ALL'
}